/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AboutUsRouteImport } from './routes/about-us'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as GroupOfCompaniesRouteImport } from './routes/group-of-companies'
import { Route as ServicesRouteImport } from './routes/services'
import { Route as ServicesIndexRouteImport } from './routes/services.index'
import { Route as ServicesAiPoweredAutomationRouteImport } from './routes/services.ai-powered-automation'
import { Route as ServicesMediaEntertainmentRouteImport } from './routes/services.media-entertainment'
import { Route as ServicesStaffingWorkforceSolutionsRouteImport } from './routes/services.staffing-workforce-solutions'

const AboutUsRoute = AboutUsRouteImport.update({
  id: '/about-us',
  path: '/about-us',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const GroupOfCompaniesRoute = GroupOfCompaniesRouteImport.update({
  id: '/group-of-companies',
  path: '/group-of-companies',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesRoute = ServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesIndexRoute = ServicesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ServicesRoute,
} as any)
const ServicesAiPoweredAutomationRoute =
  ServicesAiPoweredAutomationRouteImport.update({
    id: '/ai-powered-automation',
    path: '/ai-powered-automation',
    getParentRoute: () => ServicesRoute,
  } as any)
const ServicesMediaEntertainmentRoute =
  ServicesMediaEntertainmentRouteImport.update({
    id: '/media-entertainment',
    path: '/media-entertainment',
    getParentRoute: () => ServicesRoute,
  } as any)
const ServicesStaffingWorkforceSolutionsRoute =
  ServicesStaffingWorkforceSolutionsRouteImport.update({
    id: '/staffing-workforce-solutions',
    path: '/staffing-workforce-solutions',
    getParentRoute: () => ServicesRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/about-us': typeof AboutUsRoute
  '/contact': typeof ContactRoute
  '/group-of-companies': typeof GroupOfCompaniesRoute
  '/services': typeof ServicesRouteWithChildren
  '/services/ai-powered-automation': typeof ServicesAiPoweredAutomationRoute
  '/services/media-entertainment': typeof ServicesMediaEntertainmentRoute
  '/services/staffing-workforce-solutions': typeof ServicesStaffingWorkforceSolutionsRoute
  '/services/': typeof ServicesIndexRoute
}
export interface FileRoutesByTo {
  '/about-us': typeof AboutUsRoute
  '/contact': typeof ContactRoute
  '/group-of-companies': typeof GroupOfCompaniesRoute
  '/services/ai-powered-automation': typeof ServicesAiPoweredAutomationRoute
  '/services/media-entertainment': typeof ServicesMediaEntertainmentRoute
  '/services/staffing-workforce-solutions': typeof ServicesStaffingWorkforceSolutionsRoute
  '/services': typeof ServicesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/about-us': typeof AboutUsRoute
  '/contact': typeof ContactRoute
  '/group-of-companies': typeof GroupOfCompaniesRoute
  '/services': typeof ServicesRouteWithChildren
  '/services/ai-powered-automation': typeof ServicesAiPoweredAutomationRoute
  '/services/media-entertainment': typeof ServicesMediaEntertainmentRoute
  '/services/staffing-workforce-solutions': typeof ServicesStaffingWorkforceSolutionsRoute
  '/services/': typeof ServicesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/about-us'
    | '/contact'
    | '/group-of-companies'
    | '/services'
    | '/services/ai-powered-automation'
    | '/services/media-entertainment'
    | '/services/staffing-workforce-solutions'
    | '/services/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/about-us'
    | '/contact'
    | '/group-of-companies'
    | '/services/ai-powered-automation'
    | '/services/media-entertainment'
    | '/services/staffing-workforce-solutions'
    | '/services'
  id:
    | '__root__'
    | '/about-us'
    | '/contact'
    | '/group-of-companies'
    | '/services'
    | '/services/ai-powered-automation'
    | '/services/media-entertainment'
    | '/services/staffing-workforce-solutions'
    | '/services/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AboutUsRoute: typeof AboutUsRoute
  ContactRoute: typeof ContactRoute
  GroupOfCompaniesRoute: typeof GroupOfCompaniesRoute
  ServicesRoute: typeof ServicesRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/about-us': {
      id: '/about-us'
      path: '/about-us'
      fullPath: '/about-us'
      preLoaderRoute: typeof AboutUsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/group-of-companies': {
      id: '/group-of-companies'
      path: '/group-of-companies'
      fullPath: '/group-of-companies'
      preLoaderRoute: typeof GroupOfCompaniesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services': {
      id: '/services'
      path: '/services'
      fullPath: '/services'
      preLoaderRoute: typeof ServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/': {
      id: '/services/'
      path: '/'
      fullPath: '/services/'
      preLoaderRoute: typeof ServicesIndexRouteImport
      parentRoute: typeof ServicesRoute
    }
    '/services/ai-powered-automation': {
      id: '/services/ai-powered-automation'
      path: '/ai-powered-automation'
      fullPath: '/services/ai-powered-automation'
      preLoaderRoute: typeof ServicesAiPoweredAutomationRouteImport
      parentRoute: typeof ServicesRoute
    }
    '/services/media-entertainment': {
      id: '/services/media-entertainment'
      path: '/media-entertainment'
      fullPath: '/services/media-entertainment'
      preLoaderRoute: typeof ServicesMediaEntertainmentRouteImport
      parentRoute: typeof ServicesRoute
    }
    '/services/staffing-workforce-solutions': {
      id: '/services/staffing-workforce-solutions'
      path: '/staffing-workforce-solutions'
      fullPath: '/services/staffing-workforce-solutions'
      preLoaderRoute: typeof ServicesStaffingWorkforceSolutionsRouteImport
      parentRoute: typeof ServicesRoute
    }
  }
}

interface ServicesRouteChildren {
  ServicesAiPoweredAutomationRoute: typeof ServicesAiPoweredAutomationRoute
  ServicesMediaEntertainmentRoute: typeof ServicesMediaEntertainmentRoute
  ServicesStaffingWorkforceSolutionsRoute: typeof ServicesStaffingWorkforceSolutionsRoute
  ServicesIndexRoute: typeof ServicesIndexRoute
}

const ServicesRouteChildren: ServicesRouteChildren = {
  ServicesAiPoweredAutomationRoute: ServicesAiPoweredAutomationRoute,
  ServicesMediaEntertainmentRoute: ServicesMediaEntertainmentRoute,
  ServicesStaffingWorkforceSolutionsRoute:
    ServicesStaffingWorkforceSolutionsRoute,
  ServicesIndexRoute: ServicesIndexRoute,
}

const ServicesRouteWithChildren = ServicesRoute._addFileChildren(
  ServicesRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  AboutUsRoute: AboutUsRoute,
  ContactRoute: ContactRoute,
  GroupOfCompaniesRoute: GroupOfCompaniesRoute,
  ServicesRoute: ServicesRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
